apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nux-app
  namespace: nux
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: nux.mad.itera.no
      http:
        paths:
          - backend:
              serviceName: nux-app
              servicePort: 8080
            path: /
  tls:
    - hosts:
        - nux.mad.itera.no
      secretName: app-tls-secret
