apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nux-api
  namespace: nux
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: nux-api.mad.itera.no
      http:
        paths:
          - backend:
              serviceName: nux-api
              servicePort: 6060
            path: /
  tls:
    - hosts:
        - nux-api.mad.itera.no
      secretName: api-tls-secret
